---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-ephemeral-container-exporter-metrics-monitor
  namespace: kube-ephemeral-container-exporter-system
  labels:
    app.kubernetes.io/name: kube-ephemeral-container-exporter
    app.kubernetes.io/component: controller
spec:
  jobLabel: app.kubernetes.io/name
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      path: /metrics
      port: metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-ephemeral-container-exporter
      app.kubernetes.io/component: controller
